---
- name: configuring tomcat using multiple child playbooks
  hosts: all
  tasks: 
    - name: call multiple playbooks
      include: "{{item}}"
      with_items:
        - install_tomcat.yml
        - copy_tomcat.yml
        - change_port.yml
        - restart_tomcat.yml
        - pause.yml
        - check_tomcat_response.yml  
       
