---
- name: create users and create files/dirs in users home dir
  hosts: all
  tasks: 
    - name: users creation
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"  
    - name: create files/dirs in users home dir
      file:
        name: "{{d}}"
        state: "{{e}}"
          

